#!/bin/sh
### BEGIN INIT INFO
# Provides: tomcat
# Description: Tomcat Start Stop Kill Restart
# Required-Start: $local_fs $remote_fs $network
# Required-Stop: $local_fs $remote_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
### END INIT INFO

set -e

CATALINA_HOME="/usr/local/apache-tomcat"
CATALINA_PID="/usr/local/apache-tomcat/tomcat.pid"
JRE_HOME="/usr/lib/jvm/java-8-openjdk-amd64/jre"
USER_TOMCAT="visuallabel"

export CATALINA_PID=$CATALINA_PID
export JRE_HOME=$JRE_HOME

case "$1" in
	start)
        /bin/su -m -s /bin/sh $USER_TOMCAT -c "$CATALINA_HOME/bin/catalina.sh start"
		;;
	stop)
		if [ -f "$CATALINA_PID" ]; then
			/bin/su -m -s /bin/sh $USER_TOMCAT -c "$CATALINA_HOME/bin/catalina.sh stop"
		fi
		;;
	kill)
		if [ -f "$CATALINA_PID" ]; then
			/bin/su -m -s /bin/sh $USER_TOMCAT -c "$CATALINA_HOME/bin/catalina.sh stop -force"
		fi
		;;
	restart)
		if [ -f "$CATALINA_PID" ]; then
			/bin/su -m -s /bin/sh $USER_TOMCAT -c "$CATALINA_HOME/bin/catalina.sh stop"
			sleep 1
		fi
		/bin/su -m -s /bin/sh $USER_TOMCAT -c "$CATALINA_HOME/bin/catalina.sh start"
		;;
	status)
		if [ -f "$CATALINA_PID" ]; then
			pid=`cat "$CATALINA_PID"`
			echo "Tomcat is running with pid: $pid"
		else
			echo "Tomcat is not running"
			return 3
		fi
		;;
	*)
        echo "`basename ${0}`: usage: start | stop | kill | restart"
		exit 1
		;;
esac

exit 0
