---
#This playbook deploys applications to CAFrontEnd
    
# Configure and deploy web services
- hosts: cafrontend
  user: "{{ user_name }}"
  vars_files:
   - group_vars/secrets.yml
  roles:
    - rest-api
    - web
